import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { AppApolloProvider } from '@/providers/ApolloProvider'
import { ThemeProvider } from '@/components/theme-provider/ThemeProvider'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} font-sans antialiased`}>
        <AppApolloProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </AppApolloProvider>
      </body>
    </html>
  )
}
